# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71a085cbd23b7bfe9dd86d8de7f485f50ea0f5d1dad7df1f96527a760d1329ad0872fbf9949b9f98082b80bcfe235281df1199e1c53cf13ed752143962aac5a3

test:
  secret_key_base: 5ec81029637c877b6520f2d4df2717aa03207838930778d5a226f17c9a37d36b85d3c6ce22458cf5e8d6c55dcea66c437f7f2ac483105f1ac0a9f37a9ff67326

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
